import type { Metadata } from "next";
import "@/styles/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { detectLocaleServer } from "@/core/i18n/server";
import { I18nProvider } from "@/core/i18n/context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await detectLocaleServer();
  return (
    <html
      lang={locale}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider 
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          >
            <I18nProvider initialLocale={locale}>

            {children}
            </I18nProvider>
          </ThemeProvider>
        
        
        </body>
    </html>
  );
}
