version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: a3-redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${REDIS_PASSWORD:-nopass}
    volumes:
      - ./data/redis:/data
      - .docs/redis/redis.conf/:/usr/local/etc/redis/redis.conf
    command: >
      redis-server 
      --requirepass ${REDIS_PASSWORD:-nopass}
      --appendonly yes
      --appendfsync everysec
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-nopass}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres:latest
    container_name: a3-postgres
    restart: always
    environment:
      POSTGRES_USER: a3_user
      POSTGRES_PASSWORD: nopass
      POSTGRES_DB: a3_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    #  - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis-data:
