[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "predict",
    "quantam",
    "fastapi>=0.136.1",
    "uvicorn>=0.47.0",
]

[dependency-groups]
dev = []

[tool.uv.workspace]
members = [
    "packages/predict_all",
    "packages/quantam_trade",
]
[tool.uv.sources]
predict = {workspace = true}
quantam = {workspace = true}

